name: Documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    # First, checkout your docs repository
    - name: Checkout docs repo
      uses: actions/checkout@v2
      with:
        path: cryptorick

    # Then, checkout your source code repository
    - name: Checkout source repo
      uses: actions/checkout@v2
      with:
        repository: shadymokhtar/cryptohouse
        ref: dev
        token: ${{ secrets.PAT_TOKEN }}
        path: cryptohouse

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme
        cd cryptohouse
        pip install -e .
        # If you have requirements.txt:
        # pip install -r requirements.txt

    - name: Build documentation
      run: |
        cd cryptorick/docs
        export PYTHONPATH=$PYTHONPATH:${GITHUB_WORKSPACE}/cryptohouse
        make html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./cryptorick/docs/_build/html