name: Deploy Static Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout docs repo (cryptorick)
        uses: actions/checkout@v4

      - name: Checkout main repo (cryptohouse)
        uses: actions/checkout@v4
        with:
          repository: shadymokhtar/cryptohouse
          ref: dev
          path: cryptohouse
          token: ${{ secrets.PAT_TOKEN }}

      - name: List directories (debug)
        run: |
          echo "Current directory structure:"
          ls -R

      - name: Create directories and copy docs
        run: |
          mkdir -p docs/build/html
          echo "Copying from cryptohouse/docs/build/html to docs/build/html"
          cp -r cryptohouse/docs/build/html/* docs/build/html/
          echo "Content of destination directory:"
          ls -la docs/build/html/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/build/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3