name: Documentation

on:
  push:
    branches:
      - main  # or whatever your default branch is

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: shadymokhtar/cryptohouse  # your private repo
        ref: dev  # your branch
        token: ${{ secrets.PAT_TOKEN }}  # we'll set this up next

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme  # add any other dependencies your docs need

    - name: Build documentation
      run: |
        cd docs
        make html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html