name: Documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    # First, checkout your docs repository
    - name: Checkout docs repo
      uses: actions/checkout@v2
      with:
        path: cryptorick

    # Then, checkout your source code repository
    - name: Checkout source repo
      uses: actions/checkout@v2
      with:
        repository: shadymokhtar/cryptohouse
        ref: dev
        token: ${{ secrets.PAT_TOKEN }}
        path: cryptohouse

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme
        pip install pandas google-cloud-bigquery

    - name: Prepare source code
      run: |
        # Create the correct directory structure
        mkdir -p workspace/cryptohouse
        cp -r cryptohouse/* workspace/cryptohouse/
        cp -r cryptorick/* workspace/

    - name: Build documentation
      run: |
        cd workspace/docs
        ls -la ../../  # Debug: show directory contents
        make html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./workspace/docs/_build/html